spring:
    cors:
        allowed-origins: "*"
        allow-credential: true
    # [可选]上传文件大小限制
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: 10.89.34.9
        # [必须修改] 端口号
        port: 6379
        # [可选] 数据库 DB
        database: 0
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: DataStation2025
        # [可选] 超时时间
        timeout: 3000
        # mysql数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.89.33.97:13307/vbase?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
        username: root
        password: UJMik,789
        druid:
            initialSize: 10                       # 连接池初始化连接数
            maxActive: 200                        # 连接池最大连接数
            minIdle: 5                            # 连接池最小空闲连接数
            maxWait: 6000                         # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
            keepAlive: true                       # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
            validationQuery: select 1             # 检测连接是否有效sql，要求是查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
            testWhileIdle: true                   # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            testOnBorrow: false                   # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            testOnReturn: false                   # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
            poolPreparedStatements: false         # 是否開啟PSCache，並且指定每個連線上PSCache的大小
            timeBetweenEvictionRunsMillis: 60000  # 配置間隔多久才進行一次檢測，檢測需要關閉的空閒連線，單位是毫秒
            minEvictableIdleTimeMillis: 300000    # 配置一個連線在池中最小生存的時間，單位是毫秒
            filters: stat,slf4j             # 配置监控统计拦截的filters，监控统计用的filter:sta, 日志用的filter:log4j
            useGlobalDataSourceStat: true         # 合并多个DruidDataSource的监控数据
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
            #stat-view-servlet.url-pattern: /admin/druid/*

#[可选] vbase-gb28181监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080
    ssl:
        enabled: true
        key-store: file:F:/project/smartcity/vbase/cert/vbase.p12
        key-store-password: 123456
        key-store-type: PKCS12

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 127.0.0.1
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 3101100099
    # [可选]
    id: 31011000992016000022
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: allstars

#streamserver 默认服务器配置
media:
    id: VbaseDev
    # [必须修改] streamserver服务器的内网IP
    ip: 10.89.34.9
    # [必须修改] streamserver服务器的http.port
    http-port: 8091
    # [可选] streamserver服务器的hook.admin_params=secret
    secret: a16894b4-76d9-4bf9-8b52-9f1081cac15d
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输, 必须提前在streamserver上配置该属性，不然自动配置此属性可能不成功
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现streamserver录像的管理与下载， 0 表示不使用
    record-assist-port: 18180
# [可选] 日志配置, 一般不需要改
logging:
    config: classpath:logback-spring-dev.xml

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

config:
    oauthServer: http://10.89.33.97:23307/
    clientId: b6049aeb-2ade-27fe-4a33-d7de733f0e6d
    oauthClientId: 8c740439f82ce5bda76da605fed9a1d2
    adminUsername: admin
    adminPassword: p.jFy/*mxFSCo}0KeE-C